language: perl

sudo: false

install:
  - cpanm -n URI
  - cpanm -n URI::ws
  - cpanm -n Moo
  - cpanm -n PerlX::Maybe
  - cpanm -n Protocol::WebSocket
  - cpanm -n Scalar::Util
  - cpanm -n AnyEvent

perl:
#  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

script: HARNESS_IS_VERBOSE=1 prove -lv t xt
