language: perl

sudo: false

install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n
  - cpanm -n HTTP::Proxy
  - perl maint/proxy.pl &

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - dzil test -v

env:
  global:
    - PERL_USE_UNSAFE_INC=0
    - PERL_AE_WS_C_TEST_PROXY_URL=http://localhost:3128
    - PERL_AE_WS_C_TEST_PROXY_ON=1

